# Generated by Django 4.2.3 on 2023-07-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_questionimages_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiChartData',
            fields=[
                ('piChart_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('current_exam_pi_image', models.FileField(default=None, max_length=250, null=True, upload_to='piChart/')),
                ('all_exam_pi_image', models.FileField(default=None, max_length=250, null=True, upload_to='piChart/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.candidate')),
            ],
        ),
    ]
