# Generated by Django 4.2.3 on 2023-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_pichartdata_all_exam_pi_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pichartdata',
            name='all_exam_pi_image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='piChart/'),
        ),
        migrations.AlterField(
            model_name='pichartdata',
            name='current_exam_pi_image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='piChart/'),
        ),
    ]
