# Generated by Django 4.2.3 on 2023-07-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_alter_result_not_attempted_ques_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('question_rating_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('total_times_attempted', models.IntegerField()),
                ('total_times_wrong', models.IntegerField()),
                ('total_times_right', models.IntegerField()),
                ('difficulty', models.FloatField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questionimages')),
            ],
        ),
    ]
