# Generated by Django 4.2.3 on 2023-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_questionrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrating',
            old_name='total_times_attempted',
            new_name='total_times_not_attempted',
        ),
    ]
