# Generated by Django 4.2.3 on 2023-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0011_rename_total_times_attempted_questionrating_total_times_not_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrating',
            name='difficulty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='total_times_not_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='total_times_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='total_times_wrong',
            field=models.IntegerField(default=0),
        ),
    ]
