# Generated by Django 4.2.3 on 2023-07-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_alter_questionrating_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrating',
            old_name='question_id',
            new_name='question',
        ),
    ]
