# Generated by Django 4.2.3 on 2023-07-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_rename_question_id_questionrating_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionrating',
            old_name='question',
            new_name='question_id',
        ),
    ]
