# Generated by Django 4.2.3 on 2023-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_rename_question_questionrating_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='questionimages',
            name='question_in_exam',
            field=models.CharField(default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.TextField(max_length=20),
        ),
    ]
