# Generated by Django 4.2.3 on 2023-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_candidate_email_questionimages_question_in_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.TextField(),
        ),
    ]
