# Generated by Django 4.2.3 on 2023-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0019_result_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profileImage',
            field=models.ImageField(blank=True, default='None', max_length=250, null=True, upload_to='profile_images/'),
        ),
    ]
