# Generated by Django 4.2.3 on 2023-08-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0024_test_questionex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionEx',
            new_name='QuestionExample',
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='TestExample',
        ),
    ]
