# Generated by Django 4.2.3 on 2023-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0025_rename_questionex_questionexample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionexample',
            name='ans',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='questionexample',
            name='question_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='questionexample',
            name='question_in_exam',
            field=models.CharField(default='OTHER', max_length=100),
        ),
        migrations.AddField(
            model_name='questionexample',
            name='question_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
