# Generated by Django 4.2.3 on 2023-08-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0026_questionexample_ans_questionexample_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrating',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questionexample'),
        ),
    ]
