# Generated by Django 4.2.3 on 2023-08-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0027_alter_questionrating_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questionexample')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.candidate')),
            ],
        ),
    ]
