# Generated by Django 4.2.3 on 2023-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0028_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='username',
        ),
    ]
