# Generated by Django 4.2.3 on 2023-08-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0030_userresponse_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionrating',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questionimages'),
        ),
    ]
