# Generated by Django 4.2.3 on 2023-08-07 11:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0032_remove_userresponse_question_delete_questionexample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profileImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
