# Generated by Django 4.2.3 on 2023-08-07 12:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0033_alter_candidate_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimages',
            name='question_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='question'),
        ),
    ]
