# Generated by Django 4.2.3 on 2023-08-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0034_alter_questionimages_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('test_paper_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('test_paper_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('end_time', models.TimeField(blank=True, default=None)),
                ('total_question', models.IntegerField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('question_set_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(blank=True)),
                ('test_paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.testpaper')),
            ],
        ),
    ]
