# Generated by Django 4.2.3 on 2023-08-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0035_testpaper_questionset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaperSet',
            fields=[
                ('test_paper_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('test_paper_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('end_time', models.TimeField(blank=True, default=None)),
                ('total_question', models.IntegerField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
