# Generated by Django 4.2.3 on 2023-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0037_alter_questionset_test_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaperset',
            name='code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
